# This is a basic workflow to help you get started with Actions

name: Update tracks

# Controls when the action will run. 
on:
  schedule:
    # Daily 01:00 UTC.
    - cron:  '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      # Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      # Install Poetry
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
          
      - name: Update tracks
        run: | 
          poetry shell
          drs track-update
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./raw_data
          git commit -m "Track Update"
          git push
      
